### ISSUE TITLE
serious bug

### ISSUE THREAD

**Issue by golangCasQueue** [yireyun/go-queue#10]
This esQueue whill dead at this case, And I fix the bug in here: https://github.com/golangCasQueue/casQueue

bug reappear method:
go get github.com/yireyun/go-queue
git clone https://github.com/golangCasQueue/esQueueBug
cd esQueueBug
go test -bench="."

oh!  bomb!

**Comment by yireyun** [comment]
esQueue 适合处理高并发的数据，不在内部使用 time.Sleep（）抑制CPU占有率，需要开发者根据Get() 返回的队列中待处理数量，自行调用 time.Sleep() 实现降低CPU。
谢谢！
----

EsQueue is suitable for processing high concurrency data and is not used internally time.Sleep () to suppress the CPU occupancy, developers need to call it according to the number of queues to be processed returned by get() time.Sleep () to reduce CPU.

thank you!
