### ISSUE TITLE
que.Get函数导致CPU到达100%

### ISSUE THREAD

**Issue by shscy** [yireyun/go-queue#3]
您好，我在阅读您的queue源码时，对`func (q *EsQueue) Get() (val interface{}, ok bool, quantity uint32) `实现有一些疑惑，该函数通过for循环配合`runtime.Gosched()`来实现队列的阻塞访问，假设`Get`方法调用带一个空在queue队列上，同时程序没有运行其他的goroutine, 此时CPU的占用率依然很好，因为此时没有额外的goroutine在运行，`runtime.Gosched`的执行就变得没有意义，因为调度器只有这一个goroutine可以去调度，导致这个死循环一致在占用cpu，不知道这种情况下，队列该怎样设计才能在空队列的情况下，不会占用太多的cpu。

**Comment by yireyun** [comment]
你好，在调用runtime.Gosched()之前，程序已经通过atomic.CompareAndSwapUint32()方法成功获取队列中的位置读取权，这样在进入for循环时，为了确保Put数据已经完全写入队列，才做这个runtime.Gosched()。
这个算法最有特色的地方是，GO程抢占的是Put/Get位置的位置，这个逻辑由atomic.CompareAndSwapUint32()来保证不出错。但是抢占到的Get位置，由于数据并可能没有完全写入队列，这时候就通过cache.getNo/cache.putNo的值来确认上个操作已经完成了。
