### ISSUE TITLE
队列运行结果有点问题

### ISSUE THREAD

**Issue by ha666** [yireyun/go-queue#4]
源码：
`package main

import (
	"fmt"
	gq "github.com/yireyun/go-queue"
	"time"
)

var q1 *gq.EsQueue

func init() {
	q1 = gq.NewQueue(1024 * 1024 * 10)
}

func main() {
	for i := 0; i < 100000; i++ {
		ok, _ := q1.Put(fmt.Sprintf("%d,%s", i, time.Now().String()))
		if !ok {
			fmt.Println("写入", i, "出错")
			return
		}
	}
	fmt.Println("Quantity:", q1.Quantity())
	time.Sleep(3 * time.Second)
	for i := 0; i < 8; i++ {
		go read(i)
	}
	time.Sleep(5 * time.Second)
}

func read(thread_id int) {
	start := time.Now()
	//fmt.Println("线程:", thread_id, "开始运行")
	var count int64 = 0
	for {
		_, ok, a := q1.Get()
		if !ok && a <= 0 {
			//fmt.Println(thread_id, ",", "查询没有成功", ",", a)
			break
		} else {
			count++
		}
	}
	end := time.Now()
	//fmt.Println("线程:", thread_id, "结束运行")
	fmt.Println(fmt.Sprintf("线程:%d，操作:%d次，耗时:%d毫秒。", thread_id, count, end.Sub(start).Nanoseconds()/1000000))
}
`
结果：
`
Quantity: 100000
线程:0，操作:16517次，耗时:13毫秒。
线程:4，操作:12795次，耗时:13毫秒。
线程:6，操作:15669次，耗时:13毫秒。
线程:5，操作:12793次，耗时:13毫秒。
线程:7，操作:13619次，耗时:13毫秒。
线程:1，操作:13314次，耗时:13毫秒。
线程:2，操作:14963次，耗时:13毫秒。
线程:3，操作:12531次，耗时:13毫秒。
`

我的想法是，分多个线程从同一个队列中取数据，如果每个线程取到的数据加起来应该等于总数，可现在的结果是多了。

**Comment by LuoZijun** [comment]
建议整理下代码格式, 使用

```
    ```go
    // go code ...

    ```
```

**Comment by ha666** [comment]
```go
package main

import (
	"fmt"
	gq "github.com/yireyun/go-queue"
	"time"
)

var q1 *gq.EsQueue

func init() {
	q1 = gq.NewQueue(1024 * 1024 * 10)
}

func main() {
	for i := 0; i < 100000; i++ {
		ok, _ := q1.Put(fmt.Sprintf("%d,%s", i, time.Now().String()))
		if !ok {
			fmt.Println("写入", i, "出错")
			return
		}
	}
	fmt.Println("Quantity:", q1.Quantity())
	time.Sleep(3 * time.Second)
	for i := 0; i < 8; i++ {
		go read(i)
	}
	time.Sleep(5 * time.Second)
}

func read(thread_id int) {
	start := time.Now()
	//fmt.Println("线程:", thread_id, "开始运行")
	var count int64 = 0
	for {
		_, ok, a := q1.Get()
		if !ok && a <= 0 {
			//fmt.Println(thread_id, ",", "查询没有成功", ",", a)
			break
		} else {
			count++
		}
	}
	end := time.Now()
	//fmt.Println("线程:", thread_id, "结束运行")
	fmt.Println(fmt.Sprintf("线程:%d，操作:%d次，耗时:%d毫秒。", thread_id, count, end.Sub(start).Nanoseconds()/1000000))
}
```

运行结果：
Quantity: 100000
线程:0，操作:16517次，耗时:13毫秒。
线程:4，操作:12795次，耗时:13毫秒。
线程:6，操作:15669次，耗时:13毫秒。
线程:5，操作:12793次，耗时:13毫秒。
线程:7，操作:13619次，耗时:13毫秒。
线程:1，操作:13314次，耗时:13毫秒。
线程:2，操作:14963次，耗时:13毫秒。
线程:3，操作:12531次，耗时:13毫秒。

**Comment by yireyun** [comment]
这条语句错了
```go
		_, ok, a := q1.Get()
		if !ok && a <= 0 {
			//fmt.Println(thread_id, ",", "查询没有成功", ",", a)
			break
		} else {
			count++
		}
```
应该是
```go
		_, ok, a := q1.Get()
		if !ok {
			if a <= 0 {
				//fmt.Println(thread_id, ",", "查询没有成功", ",", a)
				break
			} else {
				continue
			}
		} else {
			count++
		}
```

**Comment by ha666** [comment]
非常感谢，我测试过了，可以了。
