### ISSUE TITLE
Multi goroutines support？

### ISSUE THREAD

**Issue by ximply** [yireyun/go-queue#9]
One goroutine do puts and the other do gets, but gets nothing.
putPos increased then getPos always 0(zero)...

**Comment by yireyun** [comment]
你需要在，重复多次（建议2次）取不到数据时，增加一个 sleep（10微妙）。
主要是Get操作的GO程太多了，抢占的cpu时钟，导致Put操作很难抢到CPU时钟。

You'll need to add a sleep (10 subtleties) if you can't get the data after multiple repetitions (two is recommended).
The main reason is that there are too many GO procedures for Get operation and the preemptive CPU clock makes it difficult for Put operation to grab the CPU clock.
